# Generated by Django 5.0.7 on 2024-08-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_avatar_user_bio_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',)},
        ),
    ]
