# Generated by Django 5.0.7 on 2024-08-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='score',
        ),
    ]
